config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
has_many :doses, dependent: :destroy
has_many :ingredients, through: :doses
validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :ingredient, presence: true, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

def index
  @cocktails = Cocktail.all
end

def show
  @cocktail = Cocktail.find(params[:id])
end

def new
  @cocktail = Cocktail.new
end

def create
  @cocktail = Cocktail.new(cocktail_params)
  if @cocktail.save
      redirect_to (@cocktail)
    else
      render :new
  end
end

 private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # cocktails/:cocktail_id/doses/new
  def new
      @dose = Dose.new
      @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      render "cocktail/show"
    end
  end

  private

  def ingredient_params
    # The require method ensures that a specific parameter is present, and if it's not provided, the require method throws an error.
    # It returns an instance of ActionController::Parameters for the key passed into require. The permit method returns a copy of the parameters object, returning only the permitted keys and values. When creating a new ActiveRecord model, only the permitted attributes are passed into the model.
    @ingredient = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<h1>Index cocktail</h1>

<table>
  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= link_to cocktail.name, cocktail_path(cocktail) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Form", new_cocktail_path  %>

app/views/cocktails/new.html.erb
<h1>Let's make a cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<%= link_to "◀️", cocktails_path %>

app/views/doses/new.html.erb
<%= simple_form_for ([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>

app/views/doses/show.html.erb
<h1><%= @cocktail.name %></h1>
<ul>
<% @cocktail.doses.each do |dose| %>
  <li><%= dose.description %> of <%= dose.ingredient.name %> <%= link_to  "Delete", dose_path(dose), method: :delete, data:{ confirm: "Are you sure ?"} %>
  </li>
<% end %>
</ul>
<%= link_to  "Add More", new_cocktail_dose_path(@cocktail) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>